version: '3'

networks:
  kit-go-network:
    driver: bridge

services:
  kit_tests:
    build:
      context: .
      dockerfile: ./Dockerfile.test
    volumes:
      - $PWD:/go/src/github.com/laironacosta/kit-go
    depends_on:
      - db-test
    networks:
      - kit-go-network
  db-test:
    image: postgres:13.2
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: testdb
    restart: on-failure
    networks:
      - kit-go-network
  redis-test:
    image: redis
    ports:
      - "6379:6379"
    expose:
      - "6379"
    restart: on-failure
    networks:
      - kit-go-network
